# Generated by Django 2.2.7 on 2020-11-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poster', '0002_auto_20201111_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='movieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieId', to='Poster.Movies'),
        ),
    ]
