# Generated by Django 2.2.7 on 2020-11-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poster', '0003_auto_20201111_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='poster',
            field=models.ImageField(null=True, upload_to='Poster_Pics/'),
        ),
    ]
